describe (1..10), 'Ranges' do
  around(:each) do |t|
    puts '---------|start|*******'
    # run test
    t.run
    puts '---------|end|*******'
  end
  it '#cover' do
    expect(subject).to cover(2)
    expect(subject).to cover(2, 5)
    expect(subject).not_to cover(0, 11)
  end

  # use the block for one line, change the subject for is_expected
  # The text of title is autogenerated
  it { is_expected.to cover(2) }
  it { is_expected.to cover(2, 5) }
  it { is_expected.not_to cover(0, 11) }

  # too possible use one line with subject
  it { expect(subject).to cover(2) }
end
